from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_templates',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('fields_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_templates')),
    sa.UniqueConstraint('code', name=op.f('uq_card_templates_code'))
    )
    op.create_index(op.f('ix_card_templates_created_at'), 'card_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_card_templates_is_active'), 'card_templates', ['is_active'], unique=False)
    op.create_table('incident_categories',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('dds_profile', sa.String(length=128), nullable=True),
    sa.Column('default_difficulty', sa.Enum('basic', 'medium', 'hard', name='difficultylevel', native_enum=False, length=40), nullable=False),
    sa.Column('required_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['incident_categories.id'], name=op.f('fk_incident_categories_parent_id_incident_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_incident_categories_code'))
    )
    op.create_index(op.f('ix_incident_categories_created_at'), 'incident_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_incident_categories_dds_profile'), 'incident_categories', ['dds_profile'], unique=False)
    op.create_index(op.f('ix_incident_categories_is_active'), 'incident_categories', ['is_active'], unique=False)
    op.create_table('outbox_messages',
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'dead', name='outboxstatus', native_enum=False, length=40), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_messages'))
    )
    op.create_index('ix_outbox_status_next', 'outbox_messages', ['status', 'next_attempt_at'], unique=False)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('roles',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_table('service_states',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('running', 'stopped', 'degraded', 'unknown', name='servicestatus', native_enum=False, length=40), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_states')),
    sa.UniqueConstraint('name', name=op.f('uq_service_states_name'))
    )
    op.create_table('system_logs',
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.Enum('debug', 'info', 'warning', 'error', 'critical', name='loglevel', native_enum=False, length=40), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('logger', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_logs'))
    )
    op.create_index(op.f('ix_system_logs_at'), 'system_logs', ['at'], unique=False)
    op.create_index('ix_system_logs_at_level', 'system_logs', ['at', 'level'], unique=False)
    op.create_index(op.f('ix_system_logs_request_id'), 'system_logs', ['request_id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('active', 'blocked', 'pending', name='userstatus', native_enum=False, length=40), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index('ix_users_status_active', 'users', ['status', 'is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action', sa.Enum('login', 'login_failed', 'logout', 'create', 'update', 'delete', 'block', 'unblock', 'permission_change', 'grade_override', 'lesson_start', 'lesson_finish', 'export', 'service_control', 'config_change', 'backup', name='auditaction', native_enum=False, length=40), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_username', sa.String(length=64), nullable=True),
    sa.Column('actor_roles', sa.String(length=255), nullable=True),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('is_security', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_at'), 'audit_logs', ['at'], unique=False)
    op.create_index('ix_audit_logs_at_action', 'audit_logs', ['at', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_security'), 'audit_logs', ['is_security'], unique=False)
    op.create_index('ix_audit_logs_object', 'audit_logs', ['object_type', 'object_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_table('backup_records',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('started', 'success', 'failed', name='backupstatus', native_enum=False, length=40), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_backup_records_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_records'))
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('scenarios',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('difficulty', sa.Enum('basic', 'medium', 'hard', name='difficultylevel', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'approved', 'archived', name='scenariostatus', native_enum=False, length=40), nullable=False),
    sa.Column('origin', sa.Enum('manual', 'ai_generated', 'ai_corrected', name='scenarioorigin', native_enum=False, length=40), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('success_criteria', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('briefing', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('ml_model', sa.String(length=128), nullable=True),
    sa.Column('ml_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_scenarios_approved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_scenarios_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['incident_categories.id'], name=op.f('fk_scenarios_category_id_incident_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    op.create_index(op.f('ix_scenarios_created_at'), 'scenarios', ['created_at'], unique=False)
    op.create_index(op.f('ix_scenarios_is_active'), 'scenarios', ['is_active'], unique=False)
    op.create_index(op.f('ix_scenarios_status'), 'scenarios', ['status'], unique=False)
    op.create_index('ix_scenarios_status_difficulty', 'scenarios', ['status', 'difficulty'], unique=False)
    op.create_table('study_groups',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('curator_id', sa.Uuid(), nullable=True),
    sa.Column('dds_profile', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['curator_id'], ['users.id'], name=op.f('fk_study_groups_curator_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_groups')),
    sa.UniqueConstraint('code', name=op.f('uq_study_groups_code'))
    )
    op.create_index(op.f('ix_study_groups_created_at'), 'study_groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_study_groups_is_active'), 'study_groups', ['is_active'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_system_settings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_system_settings_key'))
    )
    op.create_index(op.f('ix_system_settings_created_at'), 'system_settings', ['created_at'], unique=False)
    op.create_table('telephony_configs',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sip_host', sa.String(length=255), nullable=False),
    sa.Column('sip_port', sa.Integer(), nullable=False),
    sa.Column('sip_domain', sa.String(length=255), nullable=True),
    sa.Column('transport', sa.String(length=16), nullable=False),
    sa.Column('codec', sa.String(length=32), nullable=False),
    sa.Column('max_latency_ms', sa.Integer(), nullable=False),
    sa.Column('record_calls', sa.Boolean(), nullable=False),
    sa.Column('audio_format', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_telephony_configs_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telephony_configs')),
    sa.UniqueConstraint('name', name=op.f('uq_telephony_configs_name'))
    )
    op.create_index(op.f('ix_telephony_configs_created_at'), 'telephony_configs', ['created_at'], unique=False)
    op.create_table('time_norms',
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.Enum('card_fill', 'card_action', name='lessonmode', native_enum=False, length=40), nullable=True),
    sa.Column('action_type', sa.Enum('call_accepted', 'field_filled', 'text_entered', 'classified', 'routed_to_dds', 'card_saved', 'card_submitted', 'card_skipped', 'call_ended', 'note_added', name='actiontype', native_enum=False, length=40), nullable=True),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['incident_categories.id'], name=op.f('fk_time_norms_category_id_incident_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_norms')),
    sa.UniqueConstraint('category_id', 'mode', 'action_type', name='time_norms_scope')
    )
    op.create_index(op.f('ix_time_norms_created_at'), 'time_norms', ['created_at'], unique=False)
    op.create_table('training_materials',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('memo', 'classifier', 'ticket', 'doc', 'audio', 'other', name='materialkind', native_enum=False, length=40), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('indexed_by_ml', sa.Boolean(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['incident_categories.id'], name=op.f('fk_training_materials_category_id_incident_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_training_materials_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_materials'))
    )
    op.create_index(op.f('ix_training_materials_created_at'), 'training_materials', ['created_at'], unique=False)
    op.create_index(op.f('ix_training_materials_is_active'), 'training_materials', ['is_active'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('assignments',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_by_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.Enum('card_fill', 'card_action', name='lessonmode', native_enum=False, length=40), nullable=False),
    sa.Column('difficulty', sa.Enum('basic', 'medium', 'hard', name='difficultylevel', native_enum=False, length=40), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('max_errors', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('group_id IS NOT NULL OR student_id IS NOT NULL', name=op.f('ck_assignments_target_required')),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_assignments_assigned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['study_groups.id'], name=op.f('fk_assignments_group_id_study_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_assignments_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_assignments_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments'))
    )
    op.create_index(op.f('ix_assignments_created_at'), 'assignments', ['created_at'], unique=False)
    op.create_index(op.f('ix_assignments_group_id'), 'assignments', ['group_id'], unique=False)
    op.create_index(op.f('ix_assignments_is_active'), 'assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_assignments_student_id'), 'assignments', ['student_id'], unique=False)
    op.create_table('generation_requests',
    sa.Column('requested_by_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.Column('difficulty', sa.Enum('basic', 'medium', 'hard', name='difficultylevel', native_enum=False, length=40), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('teacher_comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'in_progress', 'ready', 'failed', name='generationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('ml_response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['incident_categories.id'], name=op.f('fk_generation_requests_category_id_incident_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_generation_requests_requested_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_generation_requests_scenario_id_scenarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_requests'))
    )
    op.create_index(op.f('ix_generation_requests_created_at'), 'generation_requests', ['created_at'], unique=False)
    op.create_table('group_members',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['study_groups.id'], name=op.f('fk_group_members_group_id_study_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_group_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_group_members'))
    )
    op.create_table('incident_cards',
    sa.Column('card_no', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('origin', sa.Enum('generated', 'student', 'manual', name='cardorigin', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready', 'archived', name='cardstatus', native_enum=False, length=40), nullable=False),
    sa.Column('difficulty', sa.Enum('basic', 'medium', 'hard', name='difficultylevel', native_enum=False, length=40), nullable=False),
    sa.Column('caller_profile', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('expected_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('source_attempt_id', sa.Uuid(), nullable=True),
    sa.Column('audio_path', sa.String(length=512), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_incident_cards_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['incident_categories.id'], name=op.f('fk_incident_cards_category_id_incident_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_incident_cards_scenario_id_scenarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_attempt_id'], ['card_attempts.id'], name=op.f('fk_incident_cards_source_attempt_id_card_attempts'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['template_id'], ['card_templates.id'], name=op.f('fk_incident_cards_template_id_card_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_cards')),
    sa.UniqueConstraint('card_no', name=op.f('uq_incident_cards_card_no'))
    )
    op.create_index('ix_incident_cards_category_origin', 'incident_cards', ['category_id', 'origin'], unique=False)
    op.create_index(op.f('ix_incident_cards_created_at'), 'incident_cards', ['created_at'], unique=False)
    op.create_index(op.f('ix_incident_cards_is_active'), 'incident_cards', ['is_active'], unique=False)
    op.create_index('ix_incident_cards_origin_status', 'incident_cards', ['origin', 'status'], unique=False)
    op.create_index(op.f('ix_incident_cards_scenario_id'), 'incident_cards', ['scenario_id'], unique=False)
    op.create_table('progress_stats',
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts_total', sa.Integer(), nullable=False),
    sa.Column('attempts_passed', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('avg_duration_ms', sa.Integer(), nullable=True),
    sa.Column('overtime_rate', sa.Float(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('top_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['study_groups.id'], name=op.f('fk_progress_stats_group_id_study_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_progress_stats_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_stats')),
    sa.UniqueConstraint('student_id', 'group_id', 'period_start', 'period_end', name='stat_scope')
    )
    op.create_table('lessons',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.Enum('card_fill', 'card_action', name='lessonmode', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('planned', 'running', 'paused', 'finished', 'aborted', name='lessonstatus', native_enum=False, length=40), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('assignment_id', sa.Uuid(), nullable=True),
    sa.Column('category_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('card_source', sa.Enum('generated', 'student', 'mixed', name='cardsource', native_enum=False, length=40), nullable=False),
    sa.Column('difficulty', sa.Enum('basic', 'medium', 'hard', name='difficultylevel', native_enum=False, length=40), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('max_cards', sa.Integer(), nullable=True),
    sa.Column('success_criteria', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_by_id', sa.Uuid(), nullable=True),
    sa.Column('abort_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name=op.f('fk_lessons_assignment_id_assignments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finished_by_id'], ['users.id'], name=op.f('fk_lessons_finished_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['study_groups.id'], name=op.f('fk_lessons_group_id_study_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_lessons_teacher_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons'))
    )
    op.create_index(op.f('ix_lessons_created_at'), 'lessons', ['created_at'], unique=False)
    op.create_index(op.f('ix_lessons_status'), 'lessons', ['status'], unique=False)
    op.create_index('ix_lessons_status_started', 'lessons', ['status', 'started_at'], unique=False)
    op.create_index(op.f('ix_lessons_teacher_id'), 'lessons', ['teacher_id'], unique=False)
    op.create_table('scenario_references',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=True),
    sa.Column('expected_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('expected_actions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('expected_text', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('teacher_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_scenario_references_approved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['card_id'], ['incident_cards.id'], name=op.f('fk_scenario_references_card_id_incident_cards'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_references_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_references'))
    )
    op.create_index(op.f('ix_scenario_references_created_at'), 'scenario_references', ['created_at'], unique=False)
    op.create_index(op.f('ix_scenario_references_scenario_id'), 'scenario_references', ['scenario_id'], unique=False)
    op.create_table('call_records',
    sa.Column('sip_call_id', sa.String(length=128), nullable=True),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='calldirection', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('ringing', 'answered', 'missed', 'ended', 'failed', name='callstatus', native_enum=False, length=40), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('attempt_id', sa.Uuid(), nullable=True),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('caller_number', sa.String(length=32), nullable=True),
    sa.Column('callee_number', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('audio_path', sa.String(length=512), nullable=True),
    sa.Column('audio_format', sa.String(length=8), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['card_attempts.id'], name=op.f('fk_call_records_attempt_id_card_attempts'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_call_records_lesson_id_lessons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_call_records_student_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_records')),
    sa.UniqueConstraint('sip_call_id', name=op.f('uq_call_records_sip_call_id'))
    )
    op.create_index('ix_call_records_lesson_status', 'call_records', ['lesson_id', 'status'], unique=False)
    op.create_table('certificates',
    sa.Column('serial', sa.String(length=32), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('program_name', sa.String(length=255), nullable=False),
    sa.Column('issued_by_id', sa.Uuid(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('verification_code', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], name=op.f('fk_certificates_issued_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_certificates_lesson_id_lessons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_certificates_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates')),
    sa.UniqueConstraint('serial', name=op.f('uq_certificates_serial'))
    )
    op.create_index(op.f('ix_certificates_created_at'), 'certificates', ['created_at'], unique=False)
    op.create_index(op.f('ix_certificates_student_id'), 'certificates', ['student_id'], unique=False)
    op.create_table('lesson_participants',
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('invited', 'online', 'reconnecting', 'offline', 'finished', name='participantstatus', native_enum=False, length=40), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resume_token', sa.String(length=64), nullable=False),
    sa.Column('state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('cards_issued', sa.Integer(), nullable=False),
    sa.Column('cards_submitted', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_participants_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_lesson_participants_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_participants')),
    sa.UniqueConstraint('lesson_id', 'student_id', name='participant_unique')
    )
    op.create_index(op.f('ix_lesson_participants_created_at'), 'lesson_participants', ['created_at'], unique=False)
    op.create_index(op.f('ix_lesson_participants_lesson_id'), 'lesson_participants', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_participants_resume_token'), 'lesson_participants', ['resume_token'], unique=False)
    op.create_index(op.f('ix_lesson_participants_student_id'), 'lesson_participants', ['student_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('target', sa.Enum('student', 'group', 'teacher', name='recommendationtarget', native_enum=False, length=40), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('ai', 'teacher', 'system', name='evaluationsource', native_enum=False, length=40), nullable=False),
    sa.Column('based_on', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_recommendations_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['study_groups.id'], name=op.f('fk_recommendations_group_id_study_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_recommendations_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_recommendations_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_created_at'), 'recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_student_id'), 'recommendations', ['student_id'], unique=False)
    op.create_index(op.f('ix_recommendations_target'), 'recommendations', ['target'], unique=False)
    op.create_table('reports',
    sa.Column('type', sa.Enum('lesson', 'progress', 'group_stats', 'errors', 'timing', 'audit', name='reporttype', native_enum=False, length=40), nullable=False),
    sa.Column('format', sa.Enum('json', 'csv', 'pdf', 'xlsx', name='reportformat', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ready', 'failed', name='reportstatus', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('requested_by_id', sa.Uuid(), nullable=True),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('generation_ms', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['study_groups.id'], name=op.f('fk_reports_group_id_study_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_reports_lesson_id_lessons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_reports_requested_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_reports_student_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_lesson_id'), 'reports', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_reports_student_id'), 'reports', ['student_id'], unique=False)
    op.create_index('ix_reports_type_status', 'reports', ['type', 'status'], unique=False)
    op.create_table('card_attempts',
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('issued', 'in_progress', 'submitted', 'evaluated', 'expired', 'skipped', name='attemptstatus', native_enum=False, length=40), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('norm_seconds', sa.Integer(), nullable=False),
    sa.Column('time_delta_seconds', sa.Float(), nullable=True),
    sa.Column('is_overtime', sa.Boolean(), nullable=False),
    sa.Column('draft_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('submitted_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call_records.id'], name=op.f('fk_card_attempts_call_id_call_records'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['card_id'], ['incident_cards.id'], name=op.f('fk_card_attempts_card_id_incident_cards'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_card_attempts_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['lesson_participants.id'], name=op.f('fk_card_attempts_participant_id_lesson_participants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_id'], ['scenario_references.id'], name=op.f('fk_card_attempts_reference_id_scenario_references'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_card_attempts_scenario_id_scenarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_card_attempts_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_attempts')),
    sa.UniqueConstraint('lesson_id', 'participant_id', 'sequence_no', name='attempt_sequence')
    )
    op.create_index(op.f('ix_card_attempts_created_at'), 'card_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_card_attempts_lesson_id'), 'card_attempts', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_card_attempts_status'), 'card_attempts', ['status'], unique=False)
    op.create_index('ix_card_attempts_student_status', 'card_attempts', ['student_id', 'status'], unique=False)
    op.create_table('card_answers',
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('field_code', sa.String(length=64), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['card_attempts.id'], name=op.f('fk_card_answers_attempt_id_card_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_answers')),
    sa.UniqueConstraint('attempt_id', 'field_code', name='answer_unique')
    )
    op.create_table('evaluations',
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('ai', 'teacher', 'system', name='evaluationsource', native_enum=False, length=40), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('timing_score', sa.Float(), nullable=True),
    sa.Column('procedure_score', sa.Float(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('grammar_score', sa.Float(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('critical_error_count', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ml_model', sa.String(length=128), nullable=True),
    sa.Column('ml_version', sa.String(length=64), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('overridden_by_id', sa.Uuid(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_score', sa.Float(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('teacher_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['card_attempts.id'], name=op.f('fk_evaluations_attempt_id_card_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_evaluations_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['overridden_by_id'], ['users.id'], name=op.f('fk_evaluations_overridden_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_evaluations_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations')),
    sa.UniqueConstraint('attempt_id', name='evaluation_per_attempt')
    )
    op.create_index(op.f('ix_evaluations_created_at'), 'evaluations', ['created_at'], unique=False)
    op.create_index(op.f('ix_evaluations_lesson_id'), 'evaluations', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_evaluations_student_id'), 'evaluations', ['student_id'], unique=False)
    op.create_table('ml_results',
    sa.Column('kind', sa.Enum('generation', 'correction', 'evaluation', 'grammar', 'analytics', 'recommendation', name='mltaskkind', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('ok', 'failed', 'stubbed', name='mltaskstatus', native_enum=False, length=40), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=True),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.Column('endpoint', sa.String(length=128), nullable=False),
    sa.Column('request_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('response_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['card_attempts.id'], name=op.f('fk_ml_results_attempt_id_card_attempts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_ml_results_lesson_id_lessons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_ml_results_scenario_id_scenarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_results'))
    )
    op.create_index(op.f('ix_ml_results_created_at'), 'ml_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_ml_results_kind'), 'ml_results', ['kind'], unique=False)
    op.create_table('student_actions',
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.Enum('call_accepted', 'field_filled', 'text_entered', 'classified', 'routed_to_dds', 'card_saved', 'card_submitted', 'card_skipped', 'call_ended', 'note_added', name='actiontype', native_enum=False, length=40), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('field_code', sa.String(length=64), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('client_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offset_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['card_attempts.id'], name=op.f('fk_student_actions_attempt_id_card_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_student_actions_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_student_actions_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_actions'))
    )
    op.create_index('ix_student_actions_attempt_seq', 'student_actions', ['attempt_id', 'sequence_no'], unique=False)
    op.create_index(op.f('ix_student_actions_lesson_id'), 'student_actions', ['lesson_id'], unique=False)
    op.create_table('training_history',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('attempt_id', sa.Uuid(), nullable=True),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['card_attempts.id'], name=op.f('fk_training_history_attempt_id_card_attempts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_training_history_lesson_id_lessons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_training_history_scenario_id_scenarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_training_history_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_history'))
    )
    op.create_index('ix_training_history_student_at', 'training_history', ['student_id', 'recorded_at'], unique=False)
    op.create_table('error_records',
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('timing', 'procedure', 'data_accuracy', 'classification', 'completeness', 'grammar', 'syntax', name='errorcategory', native_enum=False, length=40), nullable=False),
    sa.Column('severity', sa.Enum('minor', 'major', 'critical', name='errorseverity', native_enum=False, length=40), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('field_code', sa.String(length=64), nullable=True),
    sa.Column('expected', sa.Text(), nullable=True),
    sa.Column('actual', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('penalty', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['card_attempts.id'], name=op.f('fk_error_records_attempt_id_card_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_error_records_evaluation_id_evaluations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_records'))
    )
    op.create_index(op.f('ix_error_records_attempt_id'), 'error_records', ['attempt_id'], unique=False)
    op.create_index('ix_error_records_category_severity', 'error_records', ['category', 'severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_error_records_category_severity', table_name='error_records')
    op.drop_index(op.f('ix_error_records_attempt_id'), table_name='error_records')
    op.drop_table('error_records')
    op.drop_index('ix_training_history_student_at', table_name='training_history')
    op.drop_table('training_history')
    op.drop_index(op.f('ix_student_actions_lesson_id'), table_name='student_actions')
    op.drop_index('ix_student_actions_attempt_seq', table_name='student_actions')
    op.drop_table('student_actions')
    op.drop_index(op.f('ix_ml_results_kind'), table_name='ml_results')
    op.drop_index(op.f('ix_ml_results_created_at'), table_name='ml_results')
    op.drop_table('ml_results')
    op.drop_index(op.f('ix_evaluations_student_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_lesson_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_created_at'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_table('card_answers')
    op.drop_index('ix_card_attempts_student_status', table_name='card_attempts')
    op.drop_index(op.f('ix_card_attempts_status'), table_name='card_attempts')
    op.drop_index(op.f('ix_card_attempts_lesson_id'), table_name='card_attempts')
    op.drop_index(op.f('ix_card_attempts_created_at'), table_name='card_attempts')
    op.drop_table('card_attempts')
    op.drop_index('ix_reports_type_status', table_name='reports')
    op.drop_index(op.f('ix_reports_student_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_lesson_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_recommendations_target'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_student_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_created_at'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_lesson_participants_student_id'), table_name='lesson_participants')
    op.drop_index(op.f('ix_lesson_participants_resume_token'), table_name='lesson_participants')
    op.drop_index(op.f('ix_lesson_participants_lesson_id'), table_name='lesson_participants')
    op.drop_index(op.f('ix_lesson_participants_created_at'), table_name='lesson_participants')
    op.drop_table('lesson_participants')
    op.drop_index(op.f('ix_certificates_student_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_created_at'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index('ix_call_records_lesson_status', table_name='call_records')
    op.drop_table('call_records')
    op.drop_index(op.f('ix_scenario_references_scenario_id'), table_name='scenario_references')
    op.drop_index(op.f('ix_scenario_references_created_at'), table_name='scenario_references')
    op.drop_table('scenario_references')
    op.drop_index(op.f('ix_lessons_teacher_id'), table_name='lessons')
    op.drop_index('ix_lessons_status_started', table_name='lessons')
    op.drop_index(op.f('ix_lessons_status'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_created_at'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_table('progress_stats')
    op.drop_index(op.f('ix_incident_cards_scenario_id'), table_name='incident_cards')
    op.drop_index('ix_incident_cards_origin_status', table_name='incident_cards')
    op.drop_index(op.f('ix_incident_cards_is_active'), table_name='incident_cards')
    op.drop_index(op.f('ix_incident_cards_created_at'), table_name='incident_cards')
    op.drop_index('ix_incident_cards_category_origin', table_name='incident_cards')
    op.drop_table('incident_cards')
    op.drop_table('group_members')
    op.drop_index(op.f('ix_generation_requests_created_at'), table_name='generation_requests')
    op.drop_table('generation_requests')
    op.drop_index(op.f('ix_assignments_student_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_is_active'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_group_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_created_at'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_training_materials_is_active'), table_name='training_materials')
    op.drop_index(op.f('ix_training_materials_created_at'), table_name='training_materials')
    op.drop_table('training_materials')
    op.drop_index(op.f('ix_time_norms_created_at'), table_name='time_norms')
    op.drop_table('time_norms')
    op.drop_index(op.f('ix_telephony_configs_created_at'), table_name='telephony_configs')
    op.drop_table('telephony_configs')
    op.drop_index(op.f('ix_system_settings_created_at'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_study_groups_is_active'), table_name='study_groups')
    op.drop_index(op.f('ix_study_groups_created_at'), table_name='study_groups')
    op.drop_table('study_groups')
    op.drop_index('ix_scenarios_status_difficulty', table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_status'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_is_active'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_created_at'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_table('role_permissions')
    op.drop_table('backup_records')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_object', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_security'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_at_action', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_status_active', table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_logs_request_id'), table_name='system_logs')
    op.drop_index('ix_system_logs_at_level', table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_at'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_table('service_states')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index('ix_outbox_status_next', table_name='outbox_messages')
    op.drop_table('outbox_messages')
    op.drop_index(op.f('ix_incident_categories_is_active'), table_name='incident_categories')
    op.drop_index(op.f('ix_incident_categories_dds_profile'), table_name='incident_categories')
    op.drop_index(op.f('ix_incident_categories_created_at'), table_name='incident_categories')
    op.drop_table('incident_categories')
    op.drop_index(op.f('ix_card_templates_is_active'), table_name='card_templates')
    op.drop_index(op.f('ix_card_templates_created_at'), table_name='card_templates')
    op.drop_table('card_templates')
    # ### end Alembic commands ###
